Alessio add discount field
CTMobi/Wubtitle-Wordpress-Plugin pull request #267
Opened 2020-08-03 14:09 UTC by cpalessio96

### All Submissions:

*   [x] Does your code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/)?
*   [x] Does your code has proper inline documentation? 

### Changes proposed in this Pull Request:
Add fields for discount code

Closes #255 .

2020-08-03 14:11 UTC, GiuseppeIuculano commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Issues
======
- Added 2
           

Coverage decreased per file
===========================
- includes/Dashboard/Settings.php  -1
         

Complexity increasing per file
==============================
- src/stripe/Components/PriceTable.js  1
- includes/Api/ApiPricingPlan.php  1
         

Clones added
============
- includes/Api/ApiPricingPlan.php  2
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/CTMobi/Wubtitle-Wordpress-Plugin/pullRequest?prid=5954708&bid=19516407)

2020-08-03 14:11 UTC, GiuseppeIuculano commented on assets/css/stripeStyle.css
> +.button-bar button, .coupon-button {
Codacy found an issue: [Expected newline after "," (selector-list-comma-newline-after)](https://app.codacy.com/gh/CTMobi/Wubtitle-Wordpress-Plugin/pullRequest?prid=5954708)

2020-08-03 14:11 UTC, GiuseppeIuculano commented on assets/css/stripeStyle.css
> +.button-bar button, .coupon-button {
Codacy found an issue: [Expected selector ".button-bar button" to come before selector "button:hover:enabled" (no-descending-specificity)](https://app.codacy.com/gh/CTMobi/Wubtitle-Wordpress-Plugin/pullRequest?prid=5954708)

2020-08-03 14:15 UTC, GiuseppeIuculano commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Issues
======
- Added 2
           

Complexity increasing per file
==============================
- includes/Api/ApiPricingPlan.php  1
- src/stripe/Components/PriceTable.js  1
         

Clones added
============
- includes/Api/ApiPricingPlan.php  2
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/CTMobi/Wubtitle-Wordpress-Plugin/pullRequest?prid=5954708&bid=19516407)

2020-08-03 14:15 UTC, GiuseppeIuculano commented on assets/css/stripeStyle.css
> +.button-bar button, .coupon-button {
Codacy found an issue: [Expected selector ".button-bar button" to come before selector "button:hover:enabled" (no-descending-specificity)](https://app.codacy.com/gh/CTMobi/Wubtitle-Wordpress-Plugin/pullRequest?prid=5954708)

2020-08-03 14:15 UTC, GiuseppeIuculano commented on assets/css/stripeStyle.css
> +.button-bar button, .coupon-button {
Codacy found an issue: [Expected newline after "," (selector-list-comma-newline-after)](https://app.codacy.com/gh/CTMobi/Wubtitle-Wordpress-Plugin/pullRequest?prid=5954708)

2020-08-03 14:18 UTC, GiuseppeIuculano commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- src/stripe/Components/PriceTable.js  1
- includes/Api/ApiPricingPlan.php  1
         

Clones added
============
- includes/Api/ApiPricingPlan.php  2
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/CTMobi/Wubtitle-Wordpress-Plugin/pullRequest?prid=5954708&bid=19516407)

2020-08-04 08:42 UTC, GiuseppeIuculano commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- includes/Api/ApiPricingPlan.php  1
- src/stripe/Components/PriceTable.js  1
         

Clones added
============
- includes/Api/ApiPricingPlan.php  2
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/CTMobi/Wubtitle-Wordpress-Plugin/pullRequest?prid=5954708&bid=19516407)

2020-08-04 15:29 UTC, HyprCoder requested changes

2020-08-04 15:29 UTC, HyprCoder commented on src/stripe/SubscriptionForm.js
> +	};
```suggestion
       const newPrice = currentPrice || false;
		setDiscountedPrice(currentPrice);
	};
```

2020-08-04 15:40 UTC, GiuseppeIuculano commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- includes/Api/ApiPricingPlan.php  1
- src/stripe/Components/PriceTable.js  1
         

Clones added
============
- includes/Api/ApiPricingPlan.php  2
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/CTMobi/Wubtitle-Wordpress-Plugin/pullRequest?prid=5954708&bid=19516407)

2020-08-04 15:44 UTC, HyprCoder approved these changes

2020-08-04 15:45 UTC, GiuseppeIuculano commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- src/stripe/Components/PriceTable.js  1
- includes/Api/ApiPricingPlan.php  1
         

Clones added
============
- includes/Api/ApiPricingPlan.php  2
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/CTMobi/Wubtitle-Wordpress-Plugin/pullRequest?prid=5954708&bid=19516407)

2020-08-04 15:53 UTC, GiuseppeIuculano commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- includes/Api/ApiPricingPlan.php  1
- src/stripe/Components/PriceTable.js  1
         

Clones added
============
- includes/Api/ApiPricingPlan.php  2
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/CTMobi/Wubtitle-Wordpress-Plugin/pullRequest?prid=5954708&bid=19516407)

2020-08-04 16:29 UTC, merged