Alessio confirm upgrade
CTMobi/Wubtitle-Wordpress-Plugin pull request #268
Opened 2020-08-04 08:25 UTC by cpalessio96

### All Submissions:

*   [x] Does your code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/)?
*   [x] Does your code has proper inline documentation? 

### Changes proposed in this Pull Request:

add support 3d secure card for upgrade plan 

Closes #258 .

2020-08-04 08:27 UTC, GiuseppeIuculano commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Coverage decreased per file
===========================
- includes/Api/ApiPricingPlan.php  -2
         

Complexity increasing per file
==============================
- assets/payment/change_plan_script.js  1
         

Complexity decreasing per file
==============================
+ src/stripe/SubscriptionForm.js  -1
+ src/stripe/UpdateForm.js  -1
+ includes/Dashboard/PaymentTemplate.php  -1
+ assets/payment/payment_template.js  -1
         

Clones added
============
- assets/payment/settings_script.js  2
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/CTMobi/Wubtitle-Wordpress-Plugin/pullRequest?prid=5959027&bid=19536256)

2020-08-04 08:41 UTC, GiuseppeIuculano commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- assets/payment/change_plan_script.js  1
         

Complexity decreasing per file
==============================
+ assets/payment/payment_template.js  -1
+ includes/Dashboard/PaymentTemplate.php  -1
+ src/stripe/UpdateForm.js  -1
+ src/stripe/SubscriptionForm.js  -1
         

Clones added
============
- assets/payment/settings_script.js  2
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/CTMobi/Wubtitle-Wordpress-Plugin/pullRequest?prid=5959027&bid=19536256)

2020-08-04 10:39 UTC, GiuseppeIuculano commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Coverage increased per file
===========================
+ includes/Api/ApiPricingPlan.php  3
         

Complexity increasing per file
==============================
- assets/payment/change_plan_script.js  1
         

Complexity decreasing per file
==============================
+ includes/Dashboard/PaymentTemplate.php  -1
+ assets/payment/payment_template.js  -1
+ src/stripe/SubscriptionForm.js  -1
+ src/stripe/UpdateForm.js  -1
         

Clones added
============
- assets/payment/settings_script.js  2
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/CTMobi/Wubtitle-Wordpress-Plugin/pullRequest?prid=5959027&bid=19536256)

2020-08-04 15:41 UTC, HyprCoder requested changes

2020-08-04 15:41 UTC, HyprCoder commented on assets/payment/change_plan_script.js
> +						window.close();
This code is duplicated in line 13-16. Remove the duplication by creating a function

2020-08-04 15:49 UTC, GiuseppeIuculano commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- assets/payment/change_plan_script.js  1
         

Complexity decreasing per file
==============================
+ src/stripe/SubscriptionForm.js  -1
+ src/stripe/UpdateForm.js  -1
+ includes/Dashboard/PaymentTemplate.php  -1
+ assets/payment/payment_template.js  -1
         

Clones added
============
- assets/payment/settings_script.js  2
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/CTMobi/Wubtitle-Wordpress-Plugin/pullRequest?prid=5959027&bid=19536256)

2020-08-04 15:51 UTC, HyprCoder submitted a review, later dismissed

2020-08-04 15:52 UTC, GiuseppeIuculano commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- assets/payment/change_plan_script.js  1
         

Complexity decreasing per file
==============================
+ src/stripe/UpdateForm.js  -1
+ includes/Dashboard/PaymentTemplate.php  -1
+ src/stripe/SubscriptionForm.js  -1
+ assets/payment/payment_template.js  -1
         

Clones added
============
- assets/payment/settings_script.js  2
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/CTMobi/Wubtitle-Wordpress-Plugin/pullRequest?prid=5959027&bid=19536256)

2020-08-05 08:32 UTC, GiuseppeIuculano commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- assets/payment/change_plan_script.js  1
         

Complexity decreasing per file
==============================
+ src/stripe/UpdateForm.js  -1
+ assets/payment/payment_template.js  -1
+ src/stripe/SubscriptionForm.js  -1
+ includes/Dashboard/PaymentTemplate.php  -1
         

Clones added
============
- assets/payment/settings_script.js  2
         

Clones removed
==============
+ includes/Api/ApiPricingPlan.php  -2
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/CTMobi/Wubtitle-Wordpress-Plugin/pullRequest?prid=5959027&bid=19536256)

2020-08-05 08:56 UTC, HyprCoder approved these changes

2020-08-05 08:56 UTC, merged