add permission callback
CTMobi/Wubtitle-Wordpress-Plugin pull request #316
Opened 2020-08-24 14:37 UTC by cpalessio96

### All Submissions:

*   [x] Does your code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/)?
*   [x] Does your code has proper inline documentation? 

### Changes proposed in this Pull Request:
moved authentication inside permission callback

2020-08-24 14:39 UTC, GiuseppeIuculano commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Complexity decreasing per file
==============================
+ includes/Api/ApiAuthUpgradePlan.php  -1
+ includes/Api/ApiLicenseValidation.php  -1
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/CTMobi/Wubtitle-Wordpress-Plugin/pullRequest?prid=6062248&bid=19855672)

2020-08-24 14:52 UTC, HyprCoder requested changes

2020-08-24 14:52 UTC, HyprCoder commented on includes/Api/ApiAuthUpgradePlan.php
> +					return JWT::decode( $jwt, $db_license_key, array( 'HS256' ) );
Rimuovi il codice duplicato usando una funzione dedicata

2020-08-24 16:29 UTC, GiuseppeIuculano commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Complexity decreasing per file
==============================
+ includes/Api/ApiAuthUpgradePlan.php  -1
+ includes/Api/ApiLicenseValidation.php  -1
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/CTMobi/Wubtitle-Wordpress-Plugin/pullRequest?prid=6062248&bid=19855672)

2020-08-25 09:07 UTC, HyprCoder requested changes

2020-08-25 09:07 UTC, HyprCoder commented on includes/Api/ApiAuthUpgradePlan.php
> +					$helpers = new Helpers();
create the helper instance in construtor

2020-08-25 09:07 UTC, GiuseppeIuculano commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Complexity decreasing per file
==============================
+ includes/Api/ApiAuthUpgradePlan.php  -1
+ includes/Api/ApiLicenseValidation.php  -1
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/CTMobi/Wubtitle-Wordpress-Plugin/pullRequest?prid=6062248&bid=19855672)

2020-08-25 14:11 UTC, GiuseppeIuculano commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Complexity decreasing per file
==============================
+ includes/Api/ApiAuthUpgradePlan.php  -1
+ includes/Api/ApiLicenseValidation.php  -1
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/CTMobi/Wubtitle-Wordpress-Plugin/pullRequest?prid=6062248&bid=19855672)

2020-08-25 14:39 UTC, GiuseppeIuculano commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Coverage increased per file
===========================
+ includes/Api/ApiStoreSubtitle.php  1
         

Complexity decreasing per file
==============================
+ includes/Api/ApiLicenseValidation.php  -1
+ includes/Api/ApiAuthUpgradePlan.php  -1
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/CTMobi/Wubtitle-Wordpress-Plugin/pullRequest?prid=6062248&bid=19855672)

2020-08-25 15:05 UTC, HyprCoder approved these changes

2020-08-25 15:05 UTC, merged