add test dashbord views
CTMobi/Wubtitle-Wordpress-Plugin pull request #355
Opened 2020-09-01 14:45 UTC by cpalessio96

### All Submissions:

*   [x] Does your code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/)?
*   [x] Does your code has proper inline documentation? 

### Changes proposed in this Pull Request:

Unit test for dashboard views

2020-09-01 14:46 UTC, GiuseppeIuculano commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Coverage increased per file
===========================
+ includes/Dashboard/PaymentTemplate.php  58
+ includes/Dashboard/CancelPage.php  77
+ includes/Loader.php  15
         

Complexity increasing per file
==============================
- tests/test-dashboard.php  2
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/CTMobi/Wubtitle-Wordpress-Plugin/pullRequest?prid=6105200&bid=19984441)

2020-09-01 14:52 UTC, GiuseppeIuculano commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- tests/test-dashboard.php  2
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/CTMobi/Wubtitle-Wordpress-Plugin/pullRequest?prid=6105200&bid=19984441)

2020-09-02 07:56 UTC, HyprCoder requested changes

2020-09-02 07:56 UTC, HyprCoder commented on tests/test-dashboard.php
> +            ),
Create a real object instead of cast it.

2020-09-03 16:36 UTC, HyprCoder approved these changes

2020-09-03 16:37 UTC, GiuseppeIuculano commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- tests/test-dashboard.php  2
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/CTMobi/Wubtitle-Wordpress-Plugin/pullRequest?prid=6105200&bid=19984441)

2020-09-04 07:31 UTC, merged