Alessio add vimeo support
CTMobi/Wubtitle-Wordpress-Plugin pull request #362
Opened 2020-09-03 15:50 UTC by cpalessio96

### All Submissions:

*   [x] Does your code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/)?
*   [x] Does your code has proper inline documentation? 

### Changes proposed in this Pull Request:
add support to vimeo for get vimeo video transription on gutenberg pages

Closes #358  .

2020-09-03 15:52 UTC, GiuseppeIuculano commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Coverage increased per file
===========================
+ includes/Api/ApiGetTranscript.php  3
         

Coverage decreased per file
===========================
- includes/Core/Sources/YouTube.php  -22
         

Complexity increasing per file
==============================
- tests/test-vimeo.php  1
- includes/Core/Sources/Vimeo.php  5
- src/block/EmbedControlPanel.js  12
- includes/Utils/VimeoHelper.php  1
- includes/Api/ApiGetTranscript.php  2
- src/block/EmbedBlock.js  3
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/CTMobi/Wubtitle-Wordpress-Plugin/pullRequest?prid=6119951&bid=20025434)

2020-09-03 16:01 UTC, GiuseppeIuculano commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Coverage increased per file
===========================
+ includes/Api/ApiGetTranscript.php  3
         

Coverage decreased per file
===========================
- includes/Core/Sources/YouTube.php  -4
         

Complexity increasing per file
==============================
- includes/Api/ApiGetTranscript.php  2
- includes/Core/Sources/Vimeo.php  5
- src/block/EmbedBlock.js  3
- tests/test-vimeo.php  1
- includes/Utils/VimeoHelper.php  1
- src/block/EmbedControlPanel.js  12
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/CTMobi/Wubtitle-Wordpress-Plugin/pullRequest?prid=6119951&bid=20025434)

2020-09-04 09:17 UTC, GiuseppeIuculano commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- tests/test-vimeo.php  1
- includes/Api/ApiGetTranscript.php  2
- src/block/EmbedControlPanel.js  12
- includes/Core/Sources/Vimeo.php  5
- src/block/EmbedBlock.js  3
- includes/Utils/VimeoHelper.php  1
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/CTMobi/Wubtitle-Wordpress-Plugin/pullRequest?prid=6119951&bid=20025434)

2020-09-04 09:30 UTC, HyprCoder requested changes

2020-09-04 09:30 UTC, HyprCoder commented on includes/Api/ApiGetTranscript.php
> +			wp_send_json_success( $transcript['data'] );
Here you should use an interface to get all the data need.

2020-09-04 09:30 UTC, HyprCoder commented on includes/Api/ApiGetTranscript.php
> +			wp_send_json_success( $response );
same here

2020-09-04 12:45 UTC, GiuseppeIuculano commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- tests/test-vimeo.php  1
- includes/Utils/VimeoHelper.php  1
- src/block/EmbedBlock.js  3
- includes/Core/Sources/Vimeo.php  5
- src/block/EmbedControlPanel.js  12
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/CTMobi/Wubtitle-Wordpress-Plugin/pullRequest?prid=6119951&bid=20025434)

2020-09-04 12:59 UTC, GiuseppeIuculano commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- includes/Core/Sources/Vimeo.php  5
- tests/test-vimeo.php  1
- src/block/EmbedBlock.js  3
- includes/Utils/VimeoHelper.php  1
- src/block/EmbedControlPanel.js  12
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/CTMobi/Wubtitle-Wordpress-Plugin/pullRequest?prid=6119951&bid=20025434)

2020-09-04 13:10 UTC, HyprCoder approved these changes

2020-09-04 13:11 UTC, merged